# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cd0bdc2509cdc72259f3d38320ad3991b5429b4d5ae39d6bfd36be94bfeb7fc025f559fba9abee145df38b84a5235130dcb88364f00a9141266409089b843f1

test:
  secret_key_base: be722c03123c9f83033a22bded2a03344824a0d918b101c4dad51c59ebb12df00ea0c3e05d8a6121103d122e986e006902f1fb2c605aa1c787ea66fc6b7ac2fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
